import SuburbDevIntelContent from './SuburbDevIntelContent';
import { ALL_SUBURBS } from '../../../lib/suburbs';

// 额外的可能出现在 DevIntel 中的区域（覆盖 Brisbane 及周边主要区域）
const EXTRA_DEVINTEL_SUBURBS = [
  'Brisbane City',
  'South Brisbane',
  'West End',
  'Woolloongabba',
  'Kangaroo Point',
  'Fortitude Valley',
  'Newstead',
  'Toowong',
  'Indooroopilly',
  'Chermside',
  'Nundah',
  'Coorparoo',
  'Mount Gravatt',
  'Holland Park',
  'Greenslopes',
  'Springwood',
  'Logan Central',
  'Browns Plains',
  'Springfield',
  'Ipswich',
  'Bowen Hills',
  'Herston',
  'Carseldine',
  'Kedron',
  'Stafford',
  'Mitchelton',
  'Everton Park',
  'Albion',
  'Clayfield',
  'Hendra',
  'Eagle Farm',
  'Bulimba',
  'Hawthorne',
  'Morningside',
  'Norman Park',
  'Camp Hill',
  'Carindale',
  'Belmont',
  'Tingalpa',
  'Wynnum',
  'Manly',
  'Annerley',
  'Moorooka',
  'Salisbury',
  'Sunnybank Hills',
  'Acacia Ridge',
  'Darra',
  'Oxley',
  'Sherwood',
  'Graceville',
  'Taringa',
  'St Lucia',
  'Kenmore',
  'Chapel Hill',
  'The Gap',
  'Ashgrove',
  'Bardon',
  'Paddington',
  'Red Hill',
  'Kelvin Grove',
  'Spring Hill',
  'New Farm',
  'Teneriffe',
  'Windsor',
  'Wilston',
  'Lutwyche',
  'Gordon Park',
  'Northgate',
  'Banyo',
  'Nudgee',
  'Sandgate',
  'Bracken Ridge',
  'Zillmere',
  'Geebung',
  'Aspley',
  'McDowall',
  'Bridgeman Downs',
  'Albany Creek',
  'Flagstone',
  'Greater Flagstone',
  'Yarrabilba',
  'Park Ridge',
  'Daisy Hill',
  'Shailer Park',
  'Loganholme',
  'Meadowbrook',
  'Beenleigh',
  'Underwood',
  'Woodridge',
  'Slacks Creek',
  'Kingston',
  'Marsden',
  'Crestmead',
  'Berrinba',
  'Karawatha',
  'Sunnybank South',
];

export async function generateStaticParams() {
  const allSuburbs = [...ALL_SUBURBS, ...EXTRA_DEVINTEL_SUBURBS];
  return allSuburbs.map(suburb => ({ suburb }));
}

export default function SuburbDevIntelPage({ params }: { params: { suburb: string } }) {
  const suburbName = decodeURIComponent(params.suburb);
  return <SuburbDevIntelContent suburb={suburbName} />;
}
