-- 添加缺少的列到 listings 表
ALTER TABLE listings ADD COLUMN IF NOT EXISTS auction_date DATE;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS sale_method TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS latitude FLOAT DEFAULT 0;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS longitude FLOAT DEFAULT 0;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS agent_name TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS agent_company TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS building_size FLOAT DEFAULT 0;
