-- Compass MVP Properties 数据导入
-- 直接在 Supabase SQL Editor 中执行此脚本

INSERT INTO properties(address, suburb, property_type, land_size, bedrooms, bathrooms) VALUES
('93 Dunedin Street, SUNNYBANK', 'Sunnybank', 'house', 638, 0, 0),
('31 Shelley Street, SUNNYBANK', 'Sunnybank', 'house', 540, 0, 0),
('5 Batford Street, SUNNYBANK', 'Sunnybank', 'house', 556, 0, 0),
('13 Dema Street, SUNNYBANK', 'Sunnybank', 'house', 456, 0, 0),
('43 Shelley Street, SUNNYBANK', 'Sunnybank', 'house', 1012, 0, 0),
('20 Valhalla Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 0),
('115 Turton Street, SUNNYBANK', 'Sunnybank', 'house', 492, 0, 0),
('11/16 Troughton Road, SUNNYBANK', 'Sunnybank', 'unit', 0, 0, 0),
('5/16 Troughton Road, SUNNYBANK', 'Sunnybank', 'unit', 0, 0, 0),
('10 Sunnybrae Street, SUNNYBANK', 'Sunnybank', 'house', 556, 0, 0),
('19/38 Dyson Avenue, SUNNYBANK', 'Sunnybank', 'house', 202, 0, 0),
('27 Headland Street, SUNNYBANK', 'Sunnybank', 'house', 567, 0, 0),
('39 Mulgowie Street, SUNNYBANK', 'Sunnybank', 'house', 633, 0, 0),
('28/18 Altandi Street, SUNNYBANK', 'Sunnybank', 'house', 240, 0, 0),
('38 Samara Street, SUNNYBANK', 'Sunnybank', 'house', 703, 0, 0),
('52 Jacinda Street, SUNNYBANK', 'Sunnybank', 'house', 685, 0, 0),
('5 Gleneagles Court, SUNNYBANK', 'Sunnybank', 'house', 1266, 0, 0),
('27 Fairbank Street, SUNNYBANK', 'Sunnybank', 'house', 450, 0, 0),
('387 Mccullough Street, SUNNYBANK', 'Sunnybank', 'house', 608, 0, 0),
('152 Beenleigh Road, SUNNYBANK', 'Sunnybank', 'house', 625, 0, 0),
('140 Dixon Street, SUNNYBANK', 'Sunnybank', 'house', 1115, 0, 0),
('4 Pember Street, SUNNYBANK', 'Sunnybank', 'house', 642, 0, 0),
('114 Dixon Street, SUNNYBANK', 'Sunnybank', 'house', 1237, 0, 0),
('558 Beenleigh Road, SUNNYBANK', 'Sunnybank', 'house', 569, 0, 0),
('8/371 Beenleigh Road, SUNNYBANK', 'Sunnybank', 'house', 0, 0, 0),
('2/152 Lister Street, SUNNYBANK', 'Sunnybank', 'house', 234, 0, 0),
('20 Lavinia Street, SUNNYBANK', 'Sunnybank', 'house', 642, 0, 0),
('7 Fairbank Street, SUNNYBANK', 'Sunnybank', 'house', 811, 0, 0),
('28 Delafield Street, SUNNYBANK', 'Sunnybank', 'house', 568, 0, 0),
('6 Meta Street, SUNNYBANK', 'Sunnybank', 'house', 744, 0, 0),
('13 Wana Street, SUNNYBANK', 'Sunnybank', 'house', 658, 0, 0),
('24 Devenish Street, SUNNYBANK', 'Sunnybank', 'house', 697, 0, 0),
('76 Woff Street, SUNNYBANK', 'Sunnybank', 'house', 1012, 0, 0),
('72 Valhalla Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 0),
('199 Mains Road, SUNNYBANK', 'Sunnybank', 'house', 635, 0, 0),
('10 Tarrawonga Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 0),
('89 Woff Street, SUNNYBANK', 'Sunnybank', 'house', 1146, 0, 0),
('2 Dunedin Street, SUNNYBANK', 'Sunnybank', 'house', 727, 0, 0),
('118 Lister Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 0),
('70 Keats Street, SUNNYBANK', 'Sunnybank', 'house', 1257, 0, 0),
('27 Samara Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 0),
('10 Mulgowie Street, SUNNYBANK', 'Sunnybank', 'house', 645, 0, 0),
('33 Dixon Street, SUNNYBANK', 'Sunnybank', 'house', 1516, 0, 0),
('206 Lister Street, SUNNYBANK', 'Sunnybank', 'house', 622, 0, 0),
('20/141 Station Road, SUNNYBANK', 'Sunnybank', 'house', 800, 0, 0),
('50 Mitchell Street, SUNNYBANK', 'Sunnybank', 'house', 1011, 0, 0),
('7/66 Station Road, SUNNYBANK', 'Sunnybank', 'house', 0, 0, 0),
('27 Lara Street, SUNNYBANK', 'Sunnybank', 'house', 622, 0, 0),
('58 Halse Street, SUNNYBANK', 'Sunnybank', 'house', 584, 0, 0),
('7 Pengana Street, SUNNYBANK', 'Sunnybank', 'house', 569, 0, 0),
('21/25 Buckingham Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 0, 0, 0),
('24/248 Padstow Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 195, 0, 0),
('45/25 Buckingham Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 186, 0, 0),
('14/16 Arcadia Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 128, 0, 0),
('57/26 Buckingham Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 177, 0, 0),
('32 McGarry Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 611, 0, 0),
('2 Fels Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 501, 0, 0),
('17 Apple Blossom Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 960, 0, 0),
('12 Totten Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 1237, 0, 0),
('7 Petrina Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 809, 0, 0),
('19/28 Holmead Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 330, 0, 0),
('10/16 Doris Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 0, 0, 0),
('2 Panache Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 868, 0, 0),
('10/68 Timaru Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 173, 0, 0),
('26 Azzure Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 670, 0, 0),
('17 Arpege Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 650, 0, 0),
('20 Liverpool Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 458, 0, 0),
('116 Bordeaux Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 677, 0, 0),
('13 Cressbrook Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 405, 0, 0),
('3 Yvonne Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 600, 0, 0),
('17/37 Slobodian Avenue, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 135, 0, 0),
('1110/8 Win Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'unit', 0, 0, 0),
('14/262 Padstow Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 151, 0, 0),
('342 Warrigal Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 809, 0, 0),
('5 Fendi Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 730, 0, 0),
('25 Cranberry Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 717, 0, 0),
('2/41 Bleasby Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 129, 0, 0),
('5 Kurru Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 852, 0, 0),
('15 Poinciana Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 650, 0, 0),
('8 Fendi Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 718, 0, 0),
('50 Langford Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 379, 0, 0),
('34 Boorala Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 713, 0, 0),
('489 Warrigal Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 674, 0, 0),
('22 Liverpool Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 458, 0, 0),
('18 Coneybeer Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 450, 0, 0),
('11 Dewberry Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 628, 0, 0),
('11 Fanfare Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 624, 0, 0),
('29 Amarna Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 693, 0, 0),
('3 Angel Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 400, 0, 0),
('1 Cressbrook Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 919, 0, 0),
('5 Savanna Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 450, 0, 0),
('32/90 Oakleaf Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 127, 0, 0),
('22 Chester Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 425, 0, 0),
('60 Bordeaux Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 889, 0, 0),
('11/142 Padstow Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 171, 0, 0),
('15 Hermitage Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 671, 0, 0),
('7/41 Bleasby Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 126, 0, 0),
('44 Liverpool Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 458, 0, 0),
('42 Colvillea Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 650, 0, 0),
('10 Savanna Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 453, 0, 0),
('46 Manmarra Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 850, 0, 0),
('5/101 Bolton Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 0, 0, 0),
('88 London Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 405, 0, 0),
('30 Tuberose Place, CALAMVALE', 'Calamvale', 'house', 639, 0, 0),
('15 Huntington Court, CALAMVALE', 'Calamvale', 'house', 935, 0, 0),
('6 Bottletree Place, CALAMVALE', 'Calamvale', 'house', 860, 0, 0),
('65/9 Eduard Place, CALAMVALE', 'Calamvale', 'house', 0, 0, 0),
('52 Semper Place, CALAMVALE', 'Calamvale', 'house', 600, 0, 0),
('10 Gulubia Place, CALAMVALE', 'Calamvale', 'house', 714, 0, 0),
('2 Waterlily Place, CALAMVALE', 'Calamvale', 'house', 726, 0, 0),
('40 Gemview St, CALAMVALE', 'Calamvale', 'house', 876, 0, 0),
('60 Menser Street, CALAMVALE', 'Calamvale', 'house', 422, 0, 0),
('31/8 Earnshaw Street, CALAMVALE', 'Calamvale', 'house', 211, 0, 0),
('10/28 Diane Court, CALAMVALE', 'Calamvale', 'house', 152, 0, 0),
('26/8 Honeysuckle Way, CALAMVALE', 'Calamvale', 'house', 0, 0, 0),
('369 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 492, 0, 0),
('25 Currajong Street, CALAMVALE', 'Calamvale', 'house', 0, 0, 0),
('65 Parklands Street, CALAMVALE', 'Calamvale', 'house', 744, 0, 0),
('26 Casuarina Crescent, CALAMVALE', 'Calamvale', 'house', 825, 0, 0),
('19 Currajong Street, CALAMVALE', 'Calamvale', 'house', 735, 0, 0),
('23 Orangetip Crescent, CALAMVALE', 'Calamvale', 'house', 700, 0, 0),
(', CALAMVALE', 'Calamvale', 'house', 237, 0, 0),
('3 Marigold Close, CALAMVALE', 'Calamvale', 'house', 870, 0, 0),
('56 Palatine Street, CALAMVALE', 'Calamvale', 'house', 660, 0, 0),
('26 Aster Place, CALAMVALE', 'Calamvale', 'house', 656, 0, 0),
('22/10 Highgrove Street, CALAMVALE', 'Calamvale', 'house', 144, 0, 0),
('69/36 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 143, 0, 0),
('3/18 Mornington Court, CALAMVALE', 'Calamvale', 'house', 205, 0, 0),
('5 Lewis Place, CALAMVALE', 'Calamvale', 'house', 451, 0, 0),
('10 Tanglebrush Place, CALAMVALE', 'Calamvale', 'house', 800, 0, 0),
('27 Gippsland Place, CALAMVALE', 'Calamvale', 'house', 451, 0, 0),
('220/85 Nottingham Road, CALAMVALE', 'Calamvale', 'unit', 150, 0, 0),
('15/77 Menser Street, CALAMVALE', 'Calamvale', 'house', 156, 0, 0),
('20/360 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 166, 0, 0),
('9/35 Clarence Street, CALAMVALE', 'Calamvale', 'house', 184, 0, 0),
('16/28 Menser Street, CALAMVALE', 'Calamvale', 'house', 162, 0, 0),
('181/85 Nottingham Road, CALAMVALE', 'Calamvale', 'house', 153, 0, 0),
('69 Honeysuckle Way, CALAMVALE', 'Calamvale', 'house', 810, 0, 0),
('20/2 Diamantina Street, CALAMVALE', 'Calamvale', 'house', 152, 0, 0),
('38/108 Menser Street, CALAMVALE', 'Calamvale', 'house', 158, 0, 0),
('54/9 Eduard Place, CALAMVALE', 'Calamvale', 'house', 134, 0, 0),
('26/20 Nicoro Place, CALAMVALE', 'Calamvale', 'house', 139, 0, 0),
('39 Injune Circuit, CALAMVALE', 'Calamvale', 'house', 500, 0, 0),
('3 Rutherglen Crescent, CALAMVALE', 'Calamvale', 'house', 600, 0, 0),
('94 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 460, 0, 0),
('19 Housman Place, CALAMVALE', 'Calamvale', 'house', 578, 0, 0),
('3 Yewleaf Place, CALAMVALE', 'Calamvale', 'house', 800, 0, 0),
('53/9 Eduard Place, CALAMVALE', 'Calamvale', 'house', 134, 0, 0),
('8 Sorbus Court, CALAMVALE', 'Calamvale', 'house', 575, 0, 0),
('30/11 Pyranees Street, CALAMVALE', 'Calamvale', 'house', 182, 0, 0),
('18/78 Ormskirk Street, CALAMVALE', 'Calamvale', 'house', 0, 0, 0),
('58/2 Diamantina Street, CALAMVALE', 'Calamvale', 'house', 0, 0, 0),
('21/64 Ormskirk Street, CALAMVALE', 'Calamvale', 'house', 152, 0, 0),
('1 Mead Place, CALAMVALE', 'Calamvale', 'house', 520, 0, 0),
('19 Earnshaw Street, CALAMVALE', 'Calamvale', 'house', 303, 0, 0);
