-- 清空现有数据
TRUNCATE TABLE sales CASCADE;
TRUNCATE TABLE properties CASCADE;

-- 插入 properties
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('30 Tuberose Place, CALAMVALE', 'Calamvale', 'house', 639, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('15 Huntington Court, CALAMVALE', 'Calamvale', 'house', 935, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('6 Bottletree Place, CALAMVALE', 'Calamvale', 'house', 860, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('65/9 Eduard Place, CALAMVALE', 'Calamvale', 'house', 0, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('52 Semper Place, CALAMVALE', 'Calamvale', 'house', 600, 0, 4, 2, 5);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10 Gulubia Place, CALAMVALE', 'Calamvale', 'house', 714, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('2 Waterlily Place, CALAMVALE', 'Calamvale', 'house', 726, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('40 Gemview St, CALAMVALE', 'Calamvale', 'house', 876, 0, 4, 2, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('60 Menser Street, CALAMVALE', 'Calamvale', 'house', 422, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('31/8 Earnshaw Street, CALAMVALE', 'Calamvale', 'house', 211, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10/28 Diane Court, CALAMVALE', 'Calamvale', 'house', 152, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('26/8 Honeysuckle Way, CALAMVALE', 'Calamvale', 'house', 0, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('369 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 492, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('25 Currajong Street, CALAMVALE', 'Calamvale', 'house', 0, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('65 Parklands Street, CALAMVALE', 'Calamvale', 'house', 744, 0, 4, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('26 Casuarina Crescent, CALAMVALE', 'Calamvale', 'house', 825, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('19 Currajong Street, CALAMVALE', 'Calamvale', 'house', 735, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('23 Orangetip Crescent, CALAMVALE', 'Calamvale', 'house', 700, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('3 Marigold Close, CALAMVALE', 'Calamvale', 'house', 870, 0, 5, 3, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('56 Palatine Street, CALAMVALE', 'Calamvale', 'house', 660, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('26 Aster Place, CALAMVALE', 'Calamvale', 'house', 656, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('22/10 Highgrove Street, CALAMVALE', 'Calamvale', 'house', 144, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('69/36 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 143, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('3/18 Mornington Court, CALAMVALE', 'Calamvale', 'house', 205, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5 Lewis Place, CALAMVALE', 'Calamvale', 'house', 451, 0, 4, 2, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10 Tanglebrush Place, CALAMVALE', 'Calamvale', 'house', 800, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('27 Gippsland Place, CALAMVALE', 'Calamvale', 'house', 451, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('220/85 Nottingham Road, CALAMVALE', 'Calamvale', 'unit', 150, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('15/77 Menser Street, CALAMVALE', 'Calamvale', 'house', 156, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('20/360 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 166, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('9/35 Clarence Street, CALAMVALE', 'Calamvale', 'house', 184, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('16/28 Menser Street, CALAMVALE', 'Calamvale', 'house', 162, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('181/85 Nottingham Road, CALAMVALE', 'Calamvale', 'house', 153, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('69 Honeysuckle Way, CALAMVALE', 'Calamvale', 'house', 810, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('20/2 Diamantina Street, CALAMVALE', 'Calamvale', 'house', 152, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('38/108 Menser Street, CALAMVALE', 'Calamvale', 'house', 158, 0, 4, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('54/9 Eduard Place, CALAMVALE', 'Calamvale', 'house', 134, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('26/20 Nicoro Place, CALAMVALE', 'Calamvale', 'house', 139, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('39 Injune Circuit, CALAMVALE', 'Calamvale', 'house', 500, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('3 Rutherglen Crescent, CALAMVALE', 'Calamvale', 'house', 600, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('94 Benhiam Street, CALAMVALE', 'Calamvale', 'house', 460, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('19 Housman Place, CALAMVALE', 'Calamvale', 'house', 578, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('3 Yewleaf Place, CALAMVALE', 'Calamvale', 'house', 800, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('53/9 Eduard Place, CALAMVALE', 'Calamvale', 'house', 134, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('8 Sorbus Court, CALAMVALE', 'Calamvale', 'house', 575, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('30/11 Pyranees Street, CALAMVALE', 'Calamvale', 'house', 182, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('18/78 Ormskirk Street, CALAMVALE', 'Calamvale', 'house', 0, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('58/2 Diamantina Street, CALAMVALE', 'Calamvale', 'house', 0, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('21/64 Ormskirk Street, CALAMVALE', 'Calamvale', 'house', 152, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('1 Mead Place, CALAMVALE', 'Calamvale', 'house', 520, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('19 Earnshaw Street, CALAMVALE', 'Calamvale', 'house', 303, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('21/25 Buckingham Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'other', 0, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('24/248 Padstow Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 195, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('45/25 Buckingham Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 186, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('14/16 Arcadia Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 128, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('57/26 Buckingham Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 177, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('32 McGarry Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 611, 0, 4, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('2 Fels Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 501, 0, 5, 3, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('17 Apple Blossom Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 960, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('12 Totten Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 1237, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('7 Petrina Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 809, 0, 5, 4, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('19/28 Holmead Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 330, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10/16 Doris Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 0, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('2 Panache Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 868, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10/68 Timaru Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 173, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('26 Azzure Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 670, 0, 5, 3, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('17 Arpege Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 650, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('20 Liverpool Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 458, 0, 3, 1, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('116 Bordeaux Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 677, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('13 Cressbrook Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 405, 0, 5, 4, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('3 Yvonne Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 600, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('17/37 Slobodian Avenue, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 135, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('1110/8 Win Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'unit', 0, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('14/262 Padstow Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 151, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('342 Warrigal Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 809, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5 Fendi Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 730, 0, 4, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('25 Cranberry Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 717, 0, 3, 5, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('2/41 Bleasby Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 129, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5 Kurru Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 852, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('15 Poinciana Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 650, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('8 Fendi Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 718, 0, 6, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('50 Langford Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 379, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('34 Boorala Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 713, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('489 Warrigal Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 674, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('22 Liverpool Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 458, 0, 4, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('18 Coneybeer Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 450, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('11 Dewberry Close, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 628, 0, 5, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('11 Fanfare Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 624, 0, 5, 4, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('29 Amarna Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 693, 0, 5, 2, 5);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('3 Angel Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 400, 0, 4, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('1 Cressbrook Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 919, 0, 5, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5 Savanna Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 450, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('32/90 Oakleaf Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 127, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('22 Chester Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 425, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('60 Bordeaux Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 889, 0, 5, 6, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('11/142 Padstow Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 171, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('15 Hermitage Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 671, 0, 6, 6, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('7/41 Bleasby Road, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 126, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('44 Liverpool Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'vacant_land', 458, 0, 0, 0, 0);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('42 Colvillea Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 650, 0, 4, 1, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10 Savanna Place, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 453, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('46 Manmarra Crescent, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 850, 0, 5, 3, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5/101 Bolton Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 0, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('88 London Street, EIGHT MILE PLAINS', 'Eight Mile Plains', 'house', 405, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('93 Dunedin Street, SUNNYBANK', 'Sunnybank', 'vacant_land', 638, 0, 0, 0, 0);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('31 Shelley Street, SUNNYBANK', 'Sunnybank', 'house', 540, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5 Batford Street, SUNNYBANK', 'Sunnybank', 'house', 556, 0, 4, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('13 Dema Street, SUNNYBANK', 'Sunnybank', 'house', 456, 0, 4, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('43 Shelley Street, SUNNYBANK', 'Sunnybank', 'house', 1012, 0, 3, 1, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('20 Valhalla Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('115 Turton Street, SUNNYBANK', 'Sunnybank', 'house', 492, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('11/16 Troughton Road, SUNNYBANK', 'Sunnybank', 'unit', 0, 0, 2, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5/16 Troughton Road, SUNNYBANK', 'Sunnybank', 'unit', 0, 0, 2, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10 Sunnybrae Street, SUNNYBANK', 'Sunnybank', 'house', 556, 0, 3, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('19/38 Dyson Avenue, SUNNYBANK', 'Sunnybank', 'house', 202, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('27 Headland Street, SUNNYBANK', 'Sunnybank', 'house', 567, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('39 Mulgowie Street, SUNNYBANK', 'Sunnybank', 'house', 633, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('28/18 Altandi Street, SUNNYBANK', 'Sunnybank', 'house', 240, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('38 Samara Street, SUNNYBANK', 'Sunnybank', 'house', 703, 0, 3, 2, 0);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('52 Jacinda Street, SUNNYBANK', 'Sunnybank', 'house', 685, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('5 Gleneagles Court, SUNNYBANK', 'Sunnybank', 'house', 1266, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('27 Fairbank Street, SUNNYBANK', 'Sunnybank', 'house', 450, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('387 Mccullough Street, SUNNYBANK', 'Sunnybank', 'house', 608, 0, 8, 4, 8);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('152 Beenleigh Road, SUNNYBANK', 'Sunnybank', 'vacant_land', 625, 0, 0, 0, 0);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('140 Dixon Street, SUNNYBANK', 'Sunnybank', 'house', 1115, 0, 3, 1, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('4 Pember Street, SUNNYBANK', 'Sunnybank', 'house', 642, 0, 4, 1, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('114 Dixon Street, SUNNYBANK', 'Sunnybank', 'house', 1237, 0, 3, 2, 6);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('558 Beenleigh Road, SUNNYBANK', 'Sunnybank', 'house', 569, 0, 3, 1, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('8/371 Beenleigh Road, SUNNYBANK', 'Sunnybank', 'house', 0, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('2/152 Lister Street, SUNNYBANK', 'Sunnybank', 'house', 234, 0, 3, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('20 Lavinia Street, SUNNYBANK', 'Sunnybank', 'house', 642, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('7 Fairbank Street, SUNNYBANK', 'Sunnybank', 'house', 811, 0, 6, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('28 Delafield Street, SUNNYBANK', 'Sunnybank', 'house', 568, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('6 Meta Street, SUNNYBANK', 'Sunnybank', 'house', 744, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('13 Wana Street, SUNNYBANK', 'Sunnybank', 'house', 658, 0, 3, 1, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('24 Devenish Street, SUNNYBANK', 'Sunnybank', 'house', 697, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('76 Woff Street, SUNNYBANK', 'Sunnybank', 'house', 1012, 0, 5, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('72 Valhalla Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 3, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('199 Mains Road, SUNNYBANK', 'Sunnybank', 'house', 635, 0, 5, 2, 5);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10 Tarrawonga Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 3, 2, 4);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('89 Woff Street, SUNNYBANK', 'Sunnybank', 'house', 1146, 0, 6, 3, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('2 Dunedin Street, SUNNYBANK', 'Sunnybank', 'house', 727, 0, 5, 4, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('118 Lister Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 4, 2, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('70 Keats Street, SUNNYBANK', 'Sunnybank', 'house', 1257, 0, 4, 2, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('27 Samara Street, SUNNYBANK', 'Sunnybank', 'house', 607, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('10 Mulgowie Street, SUNNYBANK', 'Sunnybank', 'house', 645, 0, 5, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('33 Dixon Street, SUNNYBANK', 'Sunnybank', 'house', 1516, 0, 10, 7, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('206 Lister Street, SUNNYBANK', 'Sunnybank', 'house', 622, 0, 3, 1, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('20/141 Station Road, SUNNYBANK', 'Sunnybank', 'house', 800, 0, 6, 6, 3);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('50 Mitchell Street, SUNNYBANK', 'Sunnybank', 'house', 1011, 0, 4, 3, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('7/66 Station Road, SUNNYBANK', 'Sunnybank', 'house', 0, 0, 3, 3, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('27 Lara Street, SUNNYBANK', 'Sunnybank', 'house', 622, 0, 5, 3, 1);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('58 Halse Street, SUNNYBANK', 'Sunnybank', 'house', 584, 0, 4, 2, 2);
INSERT INTO properties (address, suburb, property_type, land_size, building_size, bedrooms, bathrooms, car_spaces) VALUES ('7 Pengana Street, SUNNYBANK', 'Sunnybank', 'house', 569, 0, 3, 2, 4);

-- 插入 sales
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '30 Tuberose Place, CALAMVALE'), 1270000, '2026-02-25');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '15 Huntington Court, CALAMVALE'), 1718000, '2026-02-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '6 Bottletree Place, CALAMVALE'), 1654000, '2026-01-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '65/9 Eduard Place, CALAMVALE'), 865000, '2026-02-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '52 Semper Place, CALAMVALE'), 1425000, '2025-12-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10 Gulubia Place, CALAMVALE'), 1686000, '2026-01-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '2 Waterlily Place, CALAMVALE'), 1525000, '2026-01-14');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '40 Gemview St, CALAMVALE'), 1480000, '2026-01-29');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '60 Menser Street, CALAMVALE'), 1250000, '2025-12-25');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '31/8 Earnshaw Street, CALAMVALE'), 795000, '2026-01-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10/28 Diane Court, CALAMVALE'), 921888, '2026-01-28');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '26/8 Honeysuckle Way, CALAMVALE'), 895000, '2026-01-28');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '369 Benhiam Street, CALAMVALE'), 1580000, '2026-02-28');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '25 Currajong Street, CALAMVALE'), 1412000, '2026-01-30');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '65 Parklands Street, CALAMVALE'), 1413000, '2025-11-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '26 Casuarina Crescent, CALAMVALE'), 1670000, '2025-12-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '19 Currajong Street, CALAMVALE'), 1850000, '2025-12-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '23 Orangetip Crescent, CALAMVALE'), 1345000, '2025-11-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '3 Marigold Close, CALAMVALE'), 1690000, '2025-11-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '56 Palatine Street, CALAMVALE'), 1275000, '2025-11-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '26 Aster Place, CALAMVALE'), 1939000, '2025-11-29');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '22/10 Highgrove Street, CALAMVALE'), 825000, '2025-11-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '69/36 Benhiam Street, CALAMVALE'), 750000, '2025-11-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '3/18 Mornington Court, CALAMVALE'), 749000, '2025-11-30');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5 Lewis Place, CALAMVALE'), 1268000, '2025-11-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10 Tanglebrush Place, CALAMVALE'), 1586000, '2025-11-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '27 Gippsland Place, CALAMVALE'), 1360888, '2025-12-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '220/85 Nottingham Road, CALAMVALE'), 870000, '2025-12-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '15/77 Menser Street, CALAMVALE'), 840000, '2025-12-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '20/360 Benhiam Street, CALAMVALE'), 850000, '2025-12-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '9/35 Clarence Street, CALAMVALE'), 933000, '2025-12-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '16/28 Menser Street, CALAMVALE'), 730000, '2025-12-19');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '181/85 Nottingham Road, CALAMVALE'), 801000, '2025-11-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '69 Honeysuckle Way, CALAMVALE'), 1520000, '2025-11-01');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '20/2 Diamantina Street, CALAMVALE'), 832000, '2025-11-01');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '38/108 Menser Street, CALAMVALE'), 780000, '2025-11-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '54/9 Eduard Place, CALAMVALE'), 810000, '2025-11-03');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '26/20 Nicoro Place, CALAMVALE'), 800000, '2025-11-04');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '39 Injune Circuit, CALAMVALE'), 1600000, '2025-11-17');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '3 Rutherglen Crescent, CALAMVALE'), 1870000, '2025-11-15');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '94 Benhiam Street, CALAMVALE'), 1150000, '2025-11-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '19 Housman Place, CALAMVALE'), 1200000, '2025-11-15');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '3 Yewleaf Place, CALAMVALE'), 1950000, '2025-11-15');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '53/9 Eduard Place, CALAMVALE'), 835500, '2025-11-05');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '8 Sorbus Court, CALAMVALE'), 1395000, '2025-11-15');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '30/11 Pyranees Street, CALAMVALE'), 750000, '2025-11-11');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '18/78 Ormskirk Street, CALAMVALE'), 800000, '2025-11-09');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '58/2 Diamantina Street, CALAMVALE'), 860000, '2025-11-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '21/64 Ormskirk Street, CALAMVALE'), 870000, '2025-11-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '1 Mead Place, CALAMVALE'), 930000, '2025-11-14');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '19 Earnshaw Street, CALAMVALE'), 958000, '2025-11-03');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '21/25 Buckingham Place, EIGHT MILE PLAINS'), 910000, '2026-01-05');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '24/248 Padstow Road, EIGHT MILE PLAINS'), 955000, '2025-12-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '45/25 Buckingham Place, EIGHT MILE PLAINS'), 820000, '2025-11-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '14/16 Arcadia Street, EIGHT MILE PLAINS'), 855000, '2025-11-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '57/26 Buckingham Place, EIGHT MILE PLAINS'), 776000, '2025-11-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '32 McGarry Street, EIGHT MILE PLAINS'), 1550000, '2025-11-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '2 Fels Close, EIGHT MILE PLAINS'), 1830888, '2025-11-29');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '17 Apple Blossom Place, EIGHT MILE PLAINS'), 1800000, '2025-11-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '12 Totten Close, EIGHT MILE PLAINS'), 2550000, '2026-02-16');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '7 Petrina Street, EIGHT MILE PLAINS'), 2018000, '2025-12-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '19/28 Holmead Road, EIGHT MILE PLAINS'), 920200, '2025-11-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10/16 Doris Street, EIGHT MILE PLAINS'), 915088, '2026-02-23');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '2 Panache Close, EIGHT MILE PLAINS'), 1727000, '2025-12-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10/68 Timaru Crescent, EIGHT MILE PLAINS'), 862500, '2026-01-20');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '26 Azzure Street, EIGHT MILE PLAINS'), 2350000, '2026-02-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '17 Arpege Crescent, EIGHT MILE PLAINS'), 1575000, '2025-10-27');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '20 Liverpool Street, EIGHT MILE PLAINS'), 1069000, '2025-10-13');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '116 Bordeaux Street, EIGHT MILE PLAINS'), 1802000, '2025-10-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '13 Cressbrook Street, EIGHT MILE PLAINS'), 2120500, '2025-10-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '3 Yvonne Road, EIGHT MILE PLAINS'), 1582000, '2025-10-24');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '17/37 Slobodian Avenue, EIGHT MILE PLAINS'), 800500, '2025-10-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '1110/8 Win Street, EIGHT MILE PLAINS'), 840000, '2025-10-20');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '14/262 Padstow Road, EIGHT MILE PLAINS'), 845000, '2025-10-29');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '342 Warrigal Road, EIGHT MILE PLAINS'), 1535000, '2025-10-25');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5 Fendi Place, EIGHT MILE PLAINS'), 1625000, '2025-11-08');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '25 Cranberry Street, EIGHT MILE PLAINS'), 1917500, '2025-11-08');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '2/41 Bleasby Road, EIGHT MILE PLAINS'), 802500, '2025-11-04');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5 Kurru Street, EIGHT MILE PLAINS'), 2005000, '2025-11-08');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '15 Poinciana Place, EIGHT MILE PLAINS'), 1230000, '2025-11-13');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '8 Fendi Place, EIGHT MILE PLAINS'), 2300000, '2025-11-15');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '50 Langford Street, EIGHT MILE PLAINS'), 1551000, '2025-11-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '34 Boorala Crescent, EIGHT MILE PLAINS'), 1635000, '2025-11-21');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '489 Warrigal Road, EIGHT MILE PLAINS'), 1565000, '2025-11-14');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '22 Liverpool Street, EIGHT MILE PLAINS'), 1100000, '2025-11-14');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '18 Coneybeer Place, EIGHT MILE PLAINS'), 1528000, '2025-09-04');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '11 Dewberry Close, EIGHT MILE PLAINS'), 1725000, '2025-09-08');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '11 Fanfare Street, EIGHT MILE PLAINS'), 2100000, '2025-09-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '29 Amarna Street, EIGHT MILE PLAINS'), 1795000, '2025-09-14');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '3 Angel Street, EIGHT MILE PLAINS'), 1351000, '2025-08-30');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '1 Cressbrook Street, EIGHT MILE PLAINS'), 1821000, '2025-08-30');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5 Savanna Place, EIGHT MILE PLAINS'), 1250000, '2025-09-01');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '32/90 Oakleaf Street, EIGHT MILE PLAINS'), 786888, '2025-09-08');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '22 Chester Road, EIGHT MILE PLAINS'), 1840000, '2025-09-13');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '60 Bordeaux Street, EIGHT MILE PLAINS'), 2880800, '2025-09-20');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '11/142 Padstow Road, EIGHT MILE PLAINS'), 851108, '2025-09-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '15 Hermitage Street, EIGHT MILE PLAINS'), 1889000, '2025-09-27');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '7/41 Bleasby Road, EIGHT MILE PLAINS'), 741500, '2025-09-23');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '44 Liverpool Street, EIGHT MILE PLAINS'), 850000, '2025-09-17');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '42 Colvillea Street, EIGHT MILE PLAINS'), 1320000, '2025-09-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10 Savanna Place, EIGHT MILE PLAINS'), 1305000, '2025-10-08');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '46 Manmarra Crescent, EIGHT MILE PLAINS'), 2041888, '2025-10-13');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5/101 Bolton Street, EIGHT MILE PLAINS'), 752000, '2025-10-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '88 London Street, EIGHT MILE PLAINS'), 975000, '2025-10-13');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '93 Dunedin Street, SUNNYBANK'), 1358000, '2025-11-05');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '31 Shelley Street, SUNNYBANK'), 1780000, '2025-10-25');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5 Batford Street, SUNNYBANK'), 1400000, '2025-10-31');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '13 Dema Street, SUNNYBANK'), 1337000, '2025-12-06');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '43 Shelley Street, SUNNYBANK'), 1761000, '2025-10-25');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '20 Valhalla Street, SUNNYBANK'), 1668000, '2025-10-31');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '115 Turton Street, SUNNYBANK'), 1597000, '2025-11-01');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '11/16 Troughton Road, SUNNYBANK'), 638888, '2025-11-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5/16 Troughton Road, SUNNYBANK'), 740000, '2025-11-26');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10 Sunnybrae Street, SUNNYBANK'), 1505000, '2025-11-29');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '19/38 Dyson Avenue, SUNNYBANK'), 780000, '2025-11-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '27 Headland Street, SUNNYBANK'), 1150000, '2026-01-19');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '39 Mulgowie Street, SUNNYBANK'), 1816000, '2026-03-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '28/18 Altandi Street, SUNNYBANK'), 920000, '2026-02-17');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '38 Samara Street, SUNNYBANK'), 1455000, '2026-03-04');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '52 Jacinda Street, SUNNYBANK'), 1518000, '2025-09-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '5 Gleneagles Court, SUNNYBANK'), 2250000, '2025-08-22');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '27 Fairbank Street, SUNNYBANK'), 1645000, '2025-09-05');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '387 Mccullough Street, SUNNYBANK'), 1588000, '2025-09-18');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '152 Beenleigh Road, SUNNYBANK'), 800000, '2025-08-27');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '140 Dixon Street, SUNNYBANK'), 1560000, '2025-08-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '4 Pember Street, SUNNYBANK'), 1352500, '2025-08-21');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '114 Dixon Street, SUNNYBANK'), 1710000, '2025-08-16');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '558 Beenleigh Road, SUNNYBANK'), 1040000, '2025-08-23');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '8/371 Beenleigh Road, SUNNYBANK'), 825000, '2025-08-25');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '2/152 Lister Street, SUNNYBANK'), 750000, '2025-08-21');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '20 Lavinia Street, SUNNYBANK'), 1580000, '2025-10-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '7 Fairbank Street, SUNNYBANK'), 2180000, '2025-09-20');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '28 Delafield Street, SUNNYBANK'), 1598000, '2025-09-13');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '6 Meta Street, SUNNYBANK'), 1952000, '2025-10-16');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '13 Wana Street, SUNNYBANK'), 1280000, '2025-10-11');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '24 Devenish Street, SUNNYBANK'), 1852000, '2025-10-11');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '76 Woff Street, SUNNYBANK'), 1450000, '2025-10-11');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '72 Valhalla Street, SUNNYBANK'), 1458000, '2025-06-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '199 Mains Road, SUNNYBANK'), 1400000, '2025-07-16');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10 Tarrawonga Street, SUNNYBANK'), 1308000, '2025-06-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '89 Woff Street, SUNNYBANK'), 2178888, '2025-07-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '2 Dunedin Street, SUNNYBANK'), 1330000, '2025-05-31');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '118 Lister Street, SUNNYBANK'), 1280000, '2025-06-10');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '70 Keats Street, SUNNYBANK'), 1300000, '2025-07-28');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '27 Samara Street, SUNNYBANK'), 1200000, '2025-07-02');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '10 Mulgowie Street, SUNNYBANK'), 1782000, '2025-05-31');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '33 Dixon Street, SUNNYBANK'), 2270000, '2025-06-30');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '206 Lister Street, SUNNYBANK'), 968000, '2025-06-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '20/141 Station Road, SUNNYBANK'), 2600000, '2025-06-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '50 Mitchell Street, SUNNYBANK'), 2452000, '2025-06-07');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '7/66 Station Road, SUNNYBANK'), 915000, '2025-07-14');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '27 Lara Street, SUNNYBANK'), 1730000, '2025-07-05');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '58 Halse Street, SUNNYBANK'), 1102000, '2025-08-03');
INSERT INTO sales (property_id, sold_price, sold_date) VALUES ((SELECT id FROM properties WHERE address = '7 Pengana Street, SUNNYBANK'), 1070000, '2025-07-15');

-- 验证数据
SELECT COUNT(*) as total_properties FROM properties;
SELECT COUNT(*) as total_sales FROM sales;
SELECT COUNT(*) as properties_with_beds FROM properties WHERE bedrooms > 0;
SELECT suburb, COUNT(*) as count FROM properties GROUP BY suburb ORDER BY count DESC;